### ISSUE TITLE
* element

### ISSUE THREAD

**Issue by J3SS3HVA** [kimnikitaschijf/your-tribe-profile-card#4]
Ik zie dat je border box gebruikt voor het * element.

ik raad aan om ook een margin: 0 en een padding 0 erbij toevoegen.

```css
* {
    margin: 0;
    padding:  0;
    box-sizing: borderbox;
}
```
Dit zorgt ervoor dat alle elementen standaard een padding en margin de waarde 0 word. Uiteindelijk kan je makkelijk bepaalde elementen een andere padding en margin geven

Jouw code

https://github.com/kimnikitaschijf/your-tribe-profile-card/blob/6bb56b757a9461d6761374fae0f3477c6e7ac707/styles/style.css#L1-L12
